#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTMotor,  HTServo,  HTMotor,  none)
#pragma config(Sensor, S3,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     MPLEX,          sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     M_DRIVE_BL,    tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     M_DRIVE_FL,    tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     M_BELT,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     M_LIFT_L,      tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S2_C1_1,     M_DRIVE_BR,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     M_DRIVE_FR,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C3_1,     M_LIFT_R,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C3_2,     M_FLAG,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C2_1,    SV_BUCKET_L,          tServoContinuousRotation)
#pragma config(Servo,  srvo_S2_C2_2,    SV_HOOK,              tServoContinuousRotation)
#pragma config(Servo,  srvo_S2_C2_3,    SV_BUCKET_R,          tServoContinuousRotation)
#pragma config(Servo,  srvo_S2_C2_4,    SV_AUTO,              tServoStandard)
#pragma config(Servo,  srvo_S2_C2_5,    SV_LID,               tServoStandard)
#pragma config(Servo,  srvo_S2_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "drivers/hitechnic-sensormux.h"
#include "drivers/hitechnic-gyro.h"
#include "drivers/lego-ultrasound.h"

#include "robot.h"

const int PWR_SCAN = 100;

#define GYRO msensor_S4_1
#define SONAR msensor_S4_2



int scan_direction;
bool scored = false;
bool ramp, block, wait, debug;
int button;
int pwr_x = 0;
int pwr_y = 0;
int ramp_direction;

float rot_speed;
float heading;

void initializeRobot() {
	servo[SV_HOOK] = 245;
	servo[SV_AUTO] = 0;
	servo[SV_LID] = 255;
}

void getButton() { //gets next button press
	while (true) {
		button = nNxtButtonPressed;
		if (button != -1)
			break;
	}
	PlaySoundFile("! Click.rso");
	while(nNxtButtonPressed != -1) {
	}
}

void trackWall(int dist, int max) {
	int err = dist - USreadDist(SONAR);
	if (abs(err) > max)
		pwr_y = 0; //ignore if error is really big
	else
		pwr_y = -3*err; //try to correct for error
}

void rotateAngle(int power, float angle) {
	float target = heading + angle;
	int sign = abs(angle)/angle;
	rotate(sign*power);
	ClearTimer(T3);
	int timeout = power * angle + 1000;
	while (time1[T3] < timeout && abs(heading - target) > 3) {
		if (abs(heading - angle) < 15)
			rotate(.5*sign*power);
		else
			rotate(sign*power);
	}
	driveStop();
}

task GyroUpdate() {
	HTGYROstartCal(GYRO);
	while(true) {
		while (time1[T2] < 20) //more accurate than wait1Msec(20)
			wait1Msec(1);
		time1[T2]=0;
		rot_speed = HTGYROreadRot(GYRO);
		heading += 0.02 * rot_speed;
	}
}

task main() {
	initializeRobot();

	bDisplayDiagnostics = false;

	eraseDisplay();
	nxtDisplayCenteredBigTextLine(6, "L   R");
	getButton();

	switch (button) {
	case kRightButton:
		scan_direction = -1;
		break;
	case kLeftButton:
		scan_direction = 1;
		break;
	default:
		StopAllTasks();
	}

	eraseDisplay();
	nxtDisplayCenteredTextLine(4, "Both");
	nxtDisplayCenteredTextLine(6, "Block|Ramp");
	getButton();

	switch (button) {
	case kRightButton:
		ramp = true;
		block = false;
		break;
	case kLeftButton:
		ramp = false;
		block = true;
		break;
	case kEnterButton:
		ramp = true;
		block = true;
		break;
	default:
		StopAllTasks();
	}

	if (block && ramp) {

		eraseDisplay();
		nxtDisplayCenteredTextLine(4, "Ramp Side?");
		nxtDisplayCenteredTextLine(6, "Far|Closest|Near");
		getButton();

		switch (button) {
		case kRightButton: //near side
			ramp_direction = -scan_direction;
			break;
		case kLeftButton: //far side
			ramp_direction = scan_direction;
			break;
		case kEnterButton: //closest side based on encoders
			ramp_direction = 0;
			break;
		default:
			StopAllTasks();
		}
	}

	eraseDisplay();
	nxtDisplayCenteredBigTextLine(1, "Wait for");
	nxtDisplayCenteredBigTextLine(3, "Start?");
	nxtDisplayCenteredBigTextLine(6, "Yes  No");
	getButton();

	switch (button) {
	case kRightButton:
		wait = false;
		break;
	case kLeftButton:
		wait = true;
		break;
	default:
		StopAllTasks();
	}

	eraseDisplay();
	nxtDisplayCenteredBigTextLine(1, "Debug?");
	nxtDisplayCenteredBigTextLine(6, "Yes   No");
	getButton();

	switch (button) {
	case kRightButton:
		debug = false;
		break;
	case kLeftButton:
		debug = true;
		break;
	default:
		StopAllTasks();
	}

	//optional delay before starting autonomous
	eraseDisplay();
	nxtDisplayCenteredBigTextLine(1, "Delay?");
	nxtDisplayCenteredBigTextLine(6,"0");

	int delay = 0; //number of seconds to delay
	bool done = false;
	while(!done) {
		nxtDisplayCenteredBigTextLine(6," %d ",delay);
		getButton();
		switch (button) {
		case kRightButton:
			delay++;
			break;
		case kLeftButton:
			if (delay > 0)
				delay--;
			break;
		case kEnterButton:
			done = true;
			break;
		default:
			StopAllTasks();
		}
	}

	eraseDisplay();
	nxtDisplayCenteredBigTextLine(0, "Ready?");
	nxtDisplayCenteredBigTextLine(6, "Go!");
	getButton();

	switch (button) {
	case kEnterButton:
		break;
	default:
		StopAllTasks();
	}

	////////////////////////////////////////////////////
	//code that actually runs during match starts here//
	////////////////////////////////////////////////////

	StartTask(GyroUpdate);
	eraseDisplay();
	bDisplayDiagnostics = true; //reenable diagnostics display

	if (wait)
		waitForStart();

	wait1Msec(delay*1000);

	//just get on ramp via dead reckoning

	if (ramp && !block) {

		goForward(100);
		wait1Msec(900);

		goRight(scan_direction*100);
		wait1Msec(2100);

		driveStop();
	}

	//score block in IR goal
	else {
		pwr_x = scan_direction*PWR_SCAN;
		driveTilted(pwr_x, pwr_y);
		while (USreadDistances(SONAR) == 1) {
			//wait for it to reach the wall
		}
		//we are now at the near edge of the wall//
		nMotorEncoder[M_DRIVE_FL] = 0;
		while (USreadDist(SONAR) < 200) {

			nxtDisplayString(3, "%8d     ", nMotorEncoder[M_DRIVE_FL]);
			//nxtDisplayBigStringAt(0,50, "IR:%d   ", SensorValue[IR]);

			if (SensorValue[IR] == 5 || abs(nMotorEncoder[M_DRIVE_FL]) > 6500) {
				//TODO: use sonar instead of encoder  we see the IR beacon

				scored = true;
				//wait1Msec(80);
				driveStop();
				int near_edge = abs(nMotorEncoder[M_DRIVE_FL]);
				while (SensorValue[IR] == 5){
					trackWall(35, 100);
					driveTilted(pwr_x, pwr_y);
				}
				driveStop();
				int far_edge = abs(nMotorEncoder[M_DRIVE_FL]);
				while (abs(nMotorEncoder[M_DRIVE_FL]) > (near_edge + far_edge)/2) {
					trackWall(35, 100);
					driveTilted(-pwr_x, pwr_y);
				}
				driveStop();
				nxtDisplayString(3, "%8d     ", nMotorEncoder[M_DRIVE_FL]);

				if (ramp_direction == 0) { //if we have not already chosen a direction for the ramp
					if (abs(nMotorEncoder[M_DRIVE_FL]) > 2000) //TODO: calibrate this value, should be halfway
						ramp_direction = scan_direction;
					else
						ramp_direction = -scan_direction;
				}

				pwr_x = 0;
				pwr_y = 75;
				while(true) {
					int ir = SensorValue[IR];
					if (ir < 5){
						pwr_x = -30;
						pwr_y = 0;
					}
					if (ir > 5) {
						pwr_x = 30;
						pwr_y = 0;
					}
					else {
						pwr_x = 0;
						pwr_y = 50;
					}

					if (USreadDist(SONAR) < 30)
						break;

					//trackWall(30,50);

					driveTilted(pwr_x,pwr_y);
				}

				driveStop();

				if (debug)
					wait1Msec(1000);

				wait1Msec(300);
				servo[SV_AUTO] = 130; //score the autonomous block
				wait1Msec(400);
				servo[SV_AUTO] = 24;
				wait1Msec(100);

				if (debug)
					wait1Msec(1000);

				break;
			}
			trackWall(35, 50);
			driveTilted(pwr_x, pwr_y);
		}

		driveStop();

		if (ramp) {
			//go remaining distance

			pwr_x = ramp_direction*1.5*PWR_SCAN;
			pwr_y = -10; //get a bit away from baskets
			driveTilted(pwr_x, pwr_y);
			while(USreadDist(SONAR) < 200) {
				trackWall(45,50);
				driveTilted(pwr_x, pwr_y);
			}
			servo[SV_AUTO] = 0;
			driveStop();

			if (debug)
				wait1Msec(1000);

			//get away from baskets
			if (ramp_direction == 1)
				goForward(100);
			else
				goLeft(100);
			wait1Msec(1000);
			driveStop();

			if (debug)
				wait1Msec(1000);

			//get in front of ramp
			goForwardLeft(100);
			wait1Msec(1000);
			driveStop();

			if (debug)
				wait1Msec(1000);

			rotateAngle(75,-90);
			driveStop();

			if (debug)
				wait1Msec(1000);

			//get on ramp
			if (ramp_direction == 1)
				goLeft(100);
			else
				goRight(100);
			wait1Msec(2000);
			driveStop();

		}
	}
}
