#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTServo,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S3,     SONAR,          sensorSONAR)
#pragma config(Sensor, S4,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     M_DRIVE_BL,    tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     M_DRIVE_FL,    tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     M_BELT,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     M_LIFT_L,      tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S2_C2_1,     M_DRIVE_BR,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S2_C2_2,     M_DRIVE_FR,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S2_C3_1,     M_LIFT_R,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S2_C3_2,     M_FLAG,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    SV_SCORE,             tServoContinuousRotation)
#pragma config(Servo,  srvo_S2_C1_2,    SV_HOOK,              tServoContinuousRotation)
#pragma config(Servo,  srvo_S2_C1_3,    SV_LID,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_4,    SV_AUTO,              tServoStandard)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//lift and belt controls directly from the nxt

bool lift = true;

task main() {
	while(true) {
		while (nNxtButtonPressed == kRightButton) {
			if (lift) {
				motor[M_LIFT_R] = 100;
				motor[M_LIFT_L] = 100;
			}
			else
				motor[M_BELT] = 100;
		}
		while (nNxtButtonPressed == kLeftButton) {
			if (lift) {
				motor[M_LIFT_R] = -100;
				motor[M_LIFT_L] = -100;
			}
			else
				motor[M_BELT] = -100;
		}
		if (nNxtButtonPressed == kEnterButton) {
			while(nNxtButtonPressed != -1) {
				//wait for button release
			}
			lift = !lift;
		}
		motor[M_LIFT_R] = 0;
		motor[M_LIFT_L] = 0;
		motor[M_BELT] = 0;
	}
}
