#pragma config(Sensor, S3,     IR,             sensorHiTechnicIRSeeker600)
#pragma config(Sensor, S4,     SONAR,          sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {
	while(true) {
		float irvalue = SensorValue[IR];
		float sonarvalue = SensorValue[SONAR];
		nxtDisplayBigStringAt(0,50, "IR:%d", irvalue);
		nxtDisplayBigStringAt(0, 25, "Son:%d", sonarvalue);
	}
}
