#pragma config(Sensor, S3,     SONAR,          sensorSONAR)
#pragma config(Sensor, S4,     IR,             sensorHiTechnicIRSeeker1200)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {
	while(true) {
		nxtDisplayBigStringAt(0,50, "IR:%d   ", SensorValue[IR]);
		nxtDisplayBigStringAt(0, 25, "Son:%d  ", SensorValue[SONAR]);
	}
}
