#pragma config(Sensor, S1,     SONAR,          sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drivers/lego-ultrasound.h"

task main()
{
	while (true) {
		nxtDisplayBigTextLine(2,"%d", USreadDist(S1));
	}

}
