#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorFL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorBL,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorBR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorFR,       tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
/*
drivejx1=(100*joy1_x1)/127;
drivejx2=(100*joy1_x2)/127;
drivejy1=(100*joy1_y1)/127;
drivejy2=(100*joy1_y2)/127;
*/

#include "constants.c"
#include "JoystickDriver.c"
void InitializeRobot ()
{
	return;
}

task main()
{
	InitializeRobot();
	//waitForStart();

	while(true)
	{
writeDebugStream("%d",joy1_x1);
motor[motorFR] = (1000*joy1_x1)/127;
//	motor[motorFR]= 50;
motor[motorBR] = (1000*joy1_y1)/127;
motor[motorFL] = (1000*joy1_x1)/127;
motor[motorBL] = (1000*joy1_y1)/127;
}

}
