#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S3,     IRsensor,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     ColorSensor,    sensorI2CHiTechnicColor)
#pragma config(Motor,  motorC,          M_flag_spin,   tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     M_drive_BR,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     M_drive_BL,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     M_drive_FL,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     M_drive_FR,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     M_slide_R,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     M_slide_L,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     M_belt,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorK,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    S_score_1,            tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    S_score_2,            tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    S_flag_out,           tServoStandard)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "buttons.h"

void initializeRobot() {
	// TODO: initialize scoring servos to correct location
	return;
}


task main() {
	initializeRobot();

	waitForStart(); // Wait for the beginning of autonomous phase.

	goLeft(50); // start going left, robot should be facing baskets
	while (IRVALUE != 5) { //check to see if the ir beacon is in front of the sensor
		;
	}	
	haltAllMotors(); // stop, we have found the beacon
	goForward(15); // move towards basket
	// TODO: add wait loop here
	haltAllMotors();
	raiseBucket();
	scoreBlocks(); //scores block
	haltAllMotors();
}