#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorFL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorBL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorBR,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     motorFR,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     motorLB,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C2_1,     motorRB,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_2,     motorK,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
void InitializeRobot ()
{
	return;
}

task main()
{
	InitializeRobot();
	waitForStart();

	while(true)
	{
//moving the robot forward, back, left, right, used rotation matrix (thank Chang)
writeDebugStream("%d",joystick.joy1_x1);
motor[motorFR] = (70.7*joystick.joy1_x1)/127.0-(70.7*joystick.joy1_y1)/127.0;
motor[motorBR] = (70.7*joystick.joy1_y1)/127.0+(70.7*joystick.joy1_x1)/127.0;
motor[motorFL] = (70.7*joystick.joy1_y1)/127.0+(70.7*joystick.joy1_x1)/127.0;
motor[motorBL] = (70.7*joystick.joy1_x1)/127.0-(70.7*joystick.joy1_y1)/127.0;
//rotating robot
motor[motorFL] = (100*joystick.joy1_x2)/127;
motor[motorFR] = -(100*joystick.joy1_x2)/127;
motor[motorBL] = (100*joystick.joy1_x1)/127;
motor[motorBR] = -(100*joystick.joy1_x2)/127;
//moving the conveyer belt
motor[motorLB] = (100*joystick.joy2_x1)/127;
motor[motorRB] = (100*joystick.joy2_x1)/127;
if(joy2Btn(1) == 1)
{
	motor[motorLB] = -25;
}
if(joy1Btn(3) == 1)
{
	motor[motorLB] = 25;
}
if(joy2Btn(2) == 1)
{
	motor[motorD] = 50;
}
if(joy2Btn(4) == 1)
{
	motor[motorD] = -50;
}
}
}