#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S2,     iRsensor,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     mySonar,        sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     motorFL,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorBL,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorBR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorFR,       tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void goForward (int pwr)
{
	motor[motorFL] = pwr;
	motor[motorFR] = pwr;
	motor[motorBR] = pwr;
	motor[motorBL] = pwr;
}
void goBackward (int pwr)
{
	motor[motorFL] = -pwr;
	motor[motorFR] = -pwr;
	motor[motorBR] = -pwr;
	motor[motorBL] = -pwr;
}
void goLeft (int pwr)
{
	motor[motorFL] = -pwr;
	motor[motorFR] = pwr;
	motor[motorBR] = -pwr;
	motor[motorBL] = pwr;
}
void goRight (int pwr)
{
	motor[motorFL] = pwr;
	motor[motorFR] = -pwr;
	motor[motorBR] = pwr;
	motor[motorBL] = -pwr;
}
void LeftForward (int pwr)
{
	motor[motorFL] = 0;
	motor[motorFR] = pwr;
	motor[motorBR] = 0;
	motor[motorBL] = pwr;
}
void RightForward (int pwr)
{
	motor[motorFL] = pwr;
	motor[motorFR] = 0;
	motor[motorBR] = pwr;
	motor[motorBL] = 0;
}
void RightBackward (int pwr)
{
	motor[motorFL] = 0;
	motor[motorFR] = -pwr;
	motor[motorBR] = 0;
	motor[motorBL] = -pwr;
}
void LeftBackward (int pwr)
{
	motor[motorFL] = -pwr;
	motor[motorFR] = 0;
	motor[motorBR] = -pwr;
	motor[motorBL] = 0;
}

void halt ()
{
	motor[motorFL] = 0;
	motor[motorFR] = 0;
	motor[motorBR] = 0;
	motor[motorBL] = 0;
}


/* Test edit */
// second test edit