#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S3,     S_lightsensor,  sensorLightActive)
#pragma config(Motor,  mtr_S1_C1_1,     M_DriveFL,     tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     M_DriveBR,     tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     M_DriveFR,     tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     M_DriveBL,     tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     M_Lift,        tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     M_Unused,      tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    SV_TiltLeft,          tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    SV_TiltRight,         tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    SV_Swivel,            tServoStandard)
#pragma config(Servo,  srvo_S1_C4_4,    SV_LightSensor,       tServoStandard)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

bool  GB_liftTargetSet; //to indicate automatic target for lift
int   GI_liftTarget;    //target value
float GF_SwivelTarget; //for manual control of swivel
//float GF_TiltTarget;   //for manual control of tilt

#include "JoystickDriver.c"
#include "getJoyValues.c"
#include "constants.c"
#include "Driving.c"
#include "ServoFns.c"
#include "LiftFns.c"

#include "TrackingRoutines.c"

void globalAbort(){
	motor[M_DriveFL]=0;
	motor[M_DriveBL]=0;
	motor[M_DriveFR]=0;
	motor[M_DriveBR]=0;
	motor[M_Lift]=0;

	GB_liftTargetSet=false;
}

void initializeRobot(){

  servoChangeRate[SV_TiltLeft]        = 10;
  servoChangeRate[SV_TiltRight]       = 10;
  servoChangeRate[SV_Swivel]          = 10;
  servoChangeRate[SV_LightSensor]          = 0;

  nMotorEncoder[M_Lift]    = 0;

  servo[SV_Swivel]=C_SVSWIVELCENTER;
  servo[SV_TiltRight]=C_SVTILTRIGHTUP;
  servo[SV_TiltLeft]=C_SVTILTLEFTUP;
  servo[SV_LightSensor]=C_SVLIGHTSENSORIN;

  GB_liftTargetSet=false;


}



task main()
{

	initializeRobot();
	waitForStart();
	int locA,locB,loc;
  loc=scanForEdge(C_SVLIGHTSENSORIN,C_SVLIGHTSENSORIN-100);
  setLight(loc);

  //wait1Msec(1000);
  //trackEdge(C_SVLIGHTSENSORMXOUT,C_SVLIGHTSENSORIN,10000)
  //return;
	//loc=scanForLine(loc-30,loc+30);
  //direction=1;
  //while(putMlight(loc-direction*10)!=0); //orient to pick up desired edge for line scan case

  //putMlight(loc); //for edge scan case
  while (true) {

		trackEdge(C_SVLIGHTSENSORSTOUT,C_SVLIGHTSENSORIN,50);
		wait1Msec(50);
	}
}
