#pragma config(Sensor, S1,     HTAC,                sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


#include "drivers/hitechnic-accelerometer.h"

#define scfc 0.0000005

void integrate(int duration,float *xf,float *yf, float *zf){
	int ix,iy,iz;
	int ixa,iya,iza;
	int deltat,tp,tc;
	float dtf;
	float ax,ay,az;
	float vx,vy,vz;
	*xf=0; *yf=0; *zf=0;
	vx=0;vy=0;vz=0;
	ClearTimer(T2);
	tp=0;
	HTACreadAllAxes(HTAC, ixa,iya,iza);
	while(time1[T2]<duration){

		HTACreadAllAxes(HTAC, ix,iy,iz);
		ax=ix-ixa;ay=iy-iya;az=iz-iza;
		tc=time1[T2];
		deltat=tc-tp;
		vx+=ax*deltat;vy+=ay*deltat;vz+=az*deltat;
		dtf=(scfc*deltat);
		tp=tc;
		(*xf)+=vx*dtf;(*yf)+=vy*dtf;(*zf)+=vz*dtf;

		wait1Msec(10);
	}
}

task main()
{
	float xf,yf,zf;

  int _x_axis1 = 0;
  int _y_axis1 = 0;
  int _z_axis1 = 0;

  int _x_axis2 = 0;
  int _y_axis2 = 0;
  int _z_axis2 = 0;

  string _tmp;

  nxtDisplayCenteredTextLine(0, "HiTechnic");
  nxtDisplayCenteredBigTextLine(1, "Accel");
  nxtDisplayCenteredTextLine(3, "Test 1");
  nxtDisplayCenteredTextLine(5, "Connect sensor");
  nxtDisplayCenteredTextLine(6, "to S1");
  wait1Msec(2000);

//  PlaySound(soundBeepBeep);
//  while(bSoundActive);

  while (true) {
    eraseDisplay();

    // You can read the three axes one by one
 //   HTACreadX(HTAC, _x_axis1);
 //   HTACreadY(HTAC, _y_axis1);
 //   HTACreadZ(HTAC, _z_axis1);

    // It's better to read them all at once, if you want to know
    // all of them anyway.  It is a lot more efficient.
    clearTimer(T1);
    while(time100[T1]<40){
    if (!HTACreadAllAxes(HTAC, _x_axis1, _y_axis1, _z_axis1)) {
      nxtDisplayTextLine(4, "ERROR!!");
      wait1Msec(2000);
      StopAllTasks();
    }

    nxtDisplayTextLine(0,"HTAC Test 1");

    // We can't provide more than 2 parameters to nxtDisplayTextLine(),
    // so we'll do in two steps using StringFormat()
    nxtDisplayBIGTextLine(1, "%4d",  _x_axis1);
    nxtDisplayBIGTextLine(3, "%4d",  _y_axis1);
    nxtDisplayBIGTextLine(5, "%4d",  _z_axis1);
  }


		eraseDisplay();
    //wait1Msec(1000);

    integrate(1000,&xf,&yf,&zf);
    nxtDisplayBigTextLine(1, "%7.4f", xf);
    nxtDisplayBigTextLine(3, "%7.4f", yf);
    nxtDisplayBigTextLine(5, "%7.4f", zf);

    wait1Msec(2000);

  }

}
